# Generated by Django 3.1.2 on 2020-10-17 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0002_logger_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
