# Generated by Django 3.1.2 on 2020-10-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0003_auto_20201017_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
