# Generated by Django 3.1.2 on 2020-10-17 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0004_auto_20201017_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logger',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
